<a href="https://colab.research.google.com/github/2303A51738/Data-mining/blob/main/employee.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Load the dataset
file_path = 'employee_data.csv'  # Replace with your actual file path
df = pd.read_csv(file_path)

# Display the dataset before preprocessing
print("Dataset before preprocessing:")
print(df.head())

Dataset before preprocessing:
   Employee_ID   Age    Salary  Job_Satisfaction  Work_Hours_Per_Week
0         1001  50.0  108953.0               9.0                   36
1         1002  36.0   82995.0               8.0                   59
2         1003  29.0   70757.0               2.0                   30
3         1004  42.0   39692.0               1.0                   30
4         1005  40.0   75758.0               7.0                   54

In [ ]:
# Mean imputation for 'Age'
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Median imputation for 'Salary'
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

# Mode imputation for 'Job_Satisfaction'
df['Job_Satisfaction'] = df['Job_Satisfaction'].fillna(df['Job_Satisfaction'].mode()[0])

print("\nDataset after handling missing values:")
print(df.head())

Dataset after handling missing values:
   Employee_ID   Age    Salary  Job_Satisfaction  Work_Hours_Per_Week
0         1001  50.0  108953.0               9.0                   36
1         1002  36.0   82995.0               8.0                   59
2         1003  29.0   70757.0               2.0                   30
3         1004  42.0   39692.0               1.0                   30
4         1005  40.0   75758.0               7.0                   54

In [ ]:
# Min-Max Scaling for 'Age'
df['Age_Scaled'] = (df['Age'] - df['Age'].min()) / (df['Age'].max() - df['Age'].min())

# Min-Max Scaling for 'Salary'
df['Salary_Scaled'] = (df['Salary'] - df['Salary'].min()) / (df['Salary'].max() - df['Salary'].min())

print("\nDataset after Min-Max Scaling:")
print(df[['Age', 'Age_Scaled', 'Salary', 'Salary_Scaled']].head())

Dataset after Min-Max Scaling:
    Age  Age_Scaled    Salary  Salary_Scaled
0  50.0    0.750000  108953.0       0.877708
1  36.0    0.361111   82995.0       0.585375
2  29.0    0.166667   70757.0       0.447554
3  42.0    0.527778   39692.0       0.097707
4  40.0    0.472222   75758.0       0.503874

In [ ]:
# Min-Max Scaling for 'Age'
df['Age_Scaled'] = (df['Age'] - df['Age'].min()) / (df['Age'].max() - df['Age'].min())

# Min-Max Scaling for 'Salary'
df['Salary_Scaled'] = (df['Salary'] - df['Salary'].min()) / (df['Salary'].max() - df['Salary'].min())

print("\nDataset after Min-Max Scaling:")
print(df[['Age', 'Age_Scaled', 'Salary', 'Salary_Scaled']].head())

Dataset after Min-Max Scaling:
    Age  Age_Scaled    Salary  Salary_Scaled
0  50.0    0.750000  108953.0       0.877708
1  36.0    0.361111   82995.0       0.585375
2  29.0    0.166667   70757.0       0.447554
3  42.0    0.527778   39692.0       0.097707
4  40.0    0.472222   75758.0       0.503874

In [ ]:
# Display final preprocessed dataset
print("\nFinal Preprocessed Dataset:")
print(df.head())

Final Preprocessed Dataset:
   Employee_ID   Age    Salary  Job_Satisfaction  Work_Hours_Per_Week  \
0         1001  50.0  108953.0               9.0                   36
1         1002  36.0   82995.0               8.0                   59
2         1003  29.0   70757.0               2.0                   30
3         1004  42.0   39692.0               1.0                   30
4         1005  40.0   75758.0               7.0                   54

   Age_Scaled  Salary_Scaled
0    0.750000       0.877708
1    0.361111       0.585375
2    0.166667       0.447554
3    0.527778       0.097707
4    0.472222       0.503874

In [ ]:
# Save the preprocessed dataset
df.to_csv('preprocessed_employee_data.csv', index=False)

print("\nPreprocessed dataset saved as 'preprocessed_employee_data.csv'")

Preprocessed dataset saved as 'preprocessed_employee_data.csv'

In [ ]:
df

,Employee_ID,Age,Salary,Job_Satisfaction,Work_Hours_Per_Week,Age_Scaled,Salary_Scaled
0,1001,50.000000,108953.0,9.0,36,0.750000,0.877708
1,1002,36.000000,82995.0,8.0,59,0.361111,0.585375
2,1003,29.000000,70757.0,2.0,30,0.166667,0.447554
3,1004,42.000000,39692.0,1.0,30,0.527778,0.097707
4,1005,40.000000,75758.0,7.0,54,0.472222,0.503874
5,1006,44.000000,102409.0,7.0,56,0.583333,0.804011
6,1007,32.000000,70757.0,7.0,59,0.250000,0.447554
7,1008,32.000000,95697.0,5.0,54,0.250000,0.728422
8,1009,45.000000,67065.0,3.0,49,0.611111,0.405975
9,1010,57.000000,70757.0,8.0,42,0.944444,0.447554
10,1011,45.000000,41534.0,6.0,38,0.611111,0.118451
11,1012,39.177778,70397.0,7.0,32,0.449383,0.443500
12,1013,43.000000,31016.0,7.0,36,0.555556,0.000000
13,1014,23.000000,119789.0,1.0,35,0.000000,0.999741
14,1015,45.000000,85591.0,3.0,37,0.611111,0.614611
15,1016,51.000000,119812.0,5.0,56,0.777778,1.000000
16,1017,59.000000,53247.0,3.0,38,1.000000,0.250360
17,1018,23.000000,54300.0,1.0,59,0.000000,0.262219
18,1019,42.000000,104065.0,5.0,34,0.527778,0.822661
19,1020,54.000000,112798.0,10.0,30,0.861111,0.921010
20,1021,33.000000,39268.0,7.0,48,0.277778,0.092932
21,1022,43.000000,116807.0,7.0,39,0.555556,0.966158
22,1023,46.000000,42185.0,7.0,41,0.638889,0.125783
23,1024,48.000000,93704.0,9.0,53,0.694444,0.705978
24,1025,49.000000,70757.0,10.0,44,0.722222,0.447554
25,1026,37.000000,69099.0,7.0,56,0.388889,0.428882
26,1027,36.000000,70757.0,3.0,51,0.361111,0.447554
27,1028,24.000000,68044.0,7.0,53,0.027778,0.417001
28,1029,58.000000,81214.0,1.0,38,0.972222,0.565318
29,1030,28.000000,91228.0,4.0,49,0.138889,0.678094
30,1031,39.177778,78984.0,4.0,46,0.449383,0.540205
31,1032,30.000000,70774.0,7.0,59,0.194444,0.447745
32,1033,39.000000,32568.0,7.0,46,0.444444,0.017478
33,1034,25.000000,92592.0,7.0,55,0.055556,0.693455
34,1035,39.177778,97563.0,7.0,49,0.449383,0.749437
35,1036,35.000000,32695.0,4.0,41,0.333333,0.018909
36,1037,30.000000,78190.0,7.0,59,0.194444,0.531263
37,1038,47.000000,35258.0,7.0,36,0.666667,0.047772
38,1039,23.000000,70757.0,3.0,31,0.000000,0.447554
39,1040,39.177778,69504.0,6.0,32,0.449383,0.433443
40,1041,49.000000,63159.0,2.0,46,0.722222,0.361987
41,1042,28.000000,43986.0,10.0,34,0.138889,0.146065
42,1043,29.000000,91858.0,9.0,46,0.166667,0.685189
43,1044,56.000000,42666.0,5.0,53,0.916667,0.131200
44,1045,35.000000,68660.0,6.0,46,0.333333,0.423938
45,1046,38.000000,33561.0,4.0,56,0.416667,0.028661
46,1047,57.000000,56854.0,7.0,46,0.944444,0.290982
47,1048,25.000000,94505.0,7.0,31,0.055556,0.714998
48,1049,23.000000,82251.0,7.0,31,0.000000,0.576997
49,1050,39.177778,52662.0,9.0,57,0.449383,0.243772